#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /Applications/MPC-master/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: Array

depend: Array-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.Array $(@)

.PHONY: Array
Array:
	@$(MAKE) -f Makefile.Array all

.PHONY: Array-depend
Array-depend:
	@$(MAKE) -f Makefile.Array depend

project_name_list:
	@echo Array
